apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tripipinator
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: trip
          servicePort: 50080