apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tripipinator
  namespace: tripipinator
spec:
  rules:
  - http:
      paths:
      - path: /tripipinator
        backend:
          serviceName: trip
          servicePort: 50080